-- Create table to track document completion status for each annexe/declaration
CREATE TABLE IF NOT EXISTS annexe_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  annexe_id INTEGER NOT NULL REFERENCES case_annexes(id) ON DELETE CASCADE,
  document_name TEXT NOT NULL,
  is_completed BOOLEAN DEFAULT FALSE,
  UNIQUE(client_id, annexe_id, document_name)
);

-- Enable RLS
ALTER TABLE annexe_documents ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Allow public read access to annexe_documents" ON annexe_documents
  FOR SELECT USING (true);

CREATE POLICY "Allow public insert access to annexe_documents" ON annexe_documents
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update access to annexe_documents" ON annexe_documents
  FOR UPDATE USING (true);

CREATE POLICY "Allow public delete access to annexe_documents" ON annexe_documents
  FOR DELETE USING (true);
